name: URL Checker

on:
  # Run daily at 12AM UTC (12:00 AM Friday UTC => 8:00 PM Thursday EST)
  # schedule:
  #   - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  check_urls:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - run: go run .
        working-directory: ${{ github.workspace }}/packages/url-checker
